In [23]:
from sklearn.svm import SVR
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score


df = datasets.load_diabetes(as_frame=True).frame
df.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0

In [3]:
X=df.drop("target",axis=1)

In [4]:
y=df["target"]

In [5]:
X.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641

In [9]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42)

In [10]:
y

0      151.0
1       75.0
2      141.0
3      206.0
4      135.0
       ...
437    178.0
438    104.0
439    132.0
440    220.0
441     57.0
Name: target, Length: 442, dtype: float64

In [19]:
y_scaler=StandardScaler()
y_train_scaled=y_scaler.fit_transform(y_train.values.reshape(-1,1)).ravel()
y_test_scaled=y_scaler.transform(y_test.values.reshape(-1,1)).ravel()

In [20]:
y_train_scaled

array([ 6.89917243e-01,  1.36584298e+00,  3.20071083e-01,  1.32758304e+00,
        1.37859630e+00, -1.31235335e+00,  1.05976340e+00, -1.05728703e+00,
       -1.90061552e-01,  1.45511620e+00, -1.08279366e+00,  2.08002867e+00,
        1.21280319e+00,  1.23818601e-03,  4.85864189e-01, -4.83387817e-01,
       -9.29753873e-01, -4.06867922e-01,  1.34033635e+00,  4.73110873e-01,
        1.76119578e+00, -1.26134009e+00, -5.98167660e-01,  7.15423875e-01,
       -8.02220714e-01,  1.26381646e+00, -8.78740609e-01,  1.25106314e+00,
       -1.21032682e+00, -9.68013820e-01,  5.87890716e-01, -9.68013820e-01,
        1.16178993e+00,  2.69057819e-01, -1.42713319e+00, -3.43101343e-01,
       -1.28684672e+00, -7.63960766e-01, -6.36427608e-01,  5.75137400e-01,
        1.41685625e+00,  1.62090930e+00,  1.20004988e+00,  1.31482972e+00,
        7.79190454e-01,  1.90148225e+00,  2.05291240e-01, -1.21032682e+00,
        1.56989604e+00,  7.02670559e-01, -2.02814868e-01,  5.62384084e-01,
       -3.81361290e-01, -7.38454135e-01,  1.71018251e+00,  9.06723613e-01,
        1.41685625e+00, -6.74687555e-01, -1.26134009e+00,  5.62384084e-01,
       -1.31235335e+00,  1.25106314e+00, -1.14656024e+00,  8.42957034e-01,
       -2.92088079e-01,  7.40930507e-01, -1.51801604e-01, -6.49180923e-01,
        1.39915019e-02, -4.19621238e-01, -8.65987293e-01, -5.47154397e-01,
       -1.13380693e+00, -2.92088079e-01, -1.31235335e+00, -3.30348027e-01,
       -1.64554920e-01, -1.35061330e+00, -5.72661028e-01,  3.07317767e-01,
       -8.40480662e-01, -8.91493925e-01,  7.91943770e-01, -4.97750775e-02,
       -1.19757351e+00, -7.38454135e-01,  4.60357557e-01, -1.01902708e+00,
        1.59540267e+00,  3.58331030e-01,  7.77580812e-02,  1.16178993e+00,
        1.55714272e+00,  2.56304503e-01,  3.32824399e-01, -4.97750775e-02,
        5.36877453e-01, -2.02814868e-01, -7.25700819e-01,  1.17454325e+00,
        2.13104194e+00,  1.96524883e+00, -5.72661028e-01, -1.08279366e+00,
        3.58331030e-01,  1.32758304e+00,  9.05113971e-02,  3.07317767e-01,
        7.66437138e-01, -1.38887324e+00, -4.97750775e-02,  7.77580812e-02,
       -1.26134009e+00,  5.49630769e-01,  3.96590978e-01,  1.45511620e+00,
        1.99075546e+00, -3.94114606e-01, -1.09554698e+00, -1.04453372e+00,
        3.96590978e-01, -1.26294973e-01, -8.80350251e-02,  1.79784608e-01,
        3.07317767e-01,  1.17454325e+00, -3.70217616e-02, -3.43101343e-01,
       -9.04247241e-01,  2.27132841e+00, -2.42684457e-02, -5.72661028e-01,
       -8.14974030e-01, -1.12105361e+00,  7.66437138e-01, -8.78740609e-01,
       -3.17594711e-01, -8.27727346e-01,  1.34033635e+00,  9.57736876e-01,
        5.87890716e-01, -9.80767136e-01, -1.27409340e+00, -1.56741967e+00,
       -5.72661028e-01,  6.64410611e-01, -1.26294973e-01, -4.57881185e-01,
       -9.04247241e-01,  1.12352998e+00,  1.34033635e+00, -1.04453372e+00,
        1.16018029e-01,  3.45577715e-01, -1.64554920e-01, -1.05728703e+00,
       -2.15568184e-01,  5.24124137e-01,  3.20071083e-01, -6.61934239e-01,
       -2.92088079e-01, -1.36336661e+00,  1.03425677e+00, -9.80767136e-01,
        5.62384084e-01, -7.76714082e-01,  1.03264713e-01,  9.06723613e-01,
        1.54438941e+00,  3.71084346e-01,  1.93974220e+00, -9.29753873e-01,
       -1.26134009e+00, -1.00788341e-01,  5.36877453e-01,  9.70490192e-01,
        1.99075546e+00, -1.45263982e+00, -2.41074816e-01,  2.44987483e+00,
       -1.41437988e+00, -3.30348027e-01, -9.80767136e-01,  1.03425677e+00,
       -1.33785998e+00, -1.01902708e+00, -7.89467398e-01, -8.91493925e-01,
        1.39134962e+00, -1.26294973e-01, -1.51801604e-01,  2.38610825e+00,
       -4.96141133e-01,  5.22514495e-02,  1.51888277e+00, -8.78740609e-01,
       -8.40480662e-01,  8.42957034e-01, -1.46539314e+00, -9.42507189e-01,
        2.30797872e-01,  8.04697086e-01,  2.32234167e+00, -1.29960003e+00,
        1.50612946e+00, -4.96141133e-01, -5.59907712e-01, -2.92088079e-01,
       -1.05728703e+00,  1.54438941e+00, -4.57881185e-01, -1.64393956e+00,
       -6.87440871e-01,  1.62090930e+00,  8.55710349e-01,  1.20004988e+00,
        5.87890716e-01, -2.79334763e-01, -8.02220714e-01, -1.10830029e+00,
        6.13397348e-01, -1.03178040e+00, -8.78740609e-01,  1.54438941e+00,
        1.13628330e+00, -1.12105361e+00,  1.77394909e+00,  1.04701009e+00,
        1.13628330e+00, -8.53233977e-01, -1.46539314e+00,  8.04697086e-01,
       -7.89467398e-01,  1.81220904e+00,  1.76119578e+00, -1.51801604e-01,
       -1.32510666e+00, -1.28684672e+00, -6.36427608e-01, -1.00627377e+00,
       -4.32374554e-01, -1.51801604e-01, -1.39048289e-01, -7.00194187e-01,
       -1.13380693e+00, -4.83387817e-01,  1.00875014e+00,  1.28771345e-01,
       -7.51207450e-01, -1.21032682e+00, -1.90061552e-01, -1.13541657e-01,
        2.94564451e-01,  3.96590978e-01, -7.25700819e-01, -1.42713319e+00,
        6.00644032e-01,  1.11077667e+00, -1.07004035e+00, -9.68013820e-01,
       -1.33785998e+00, -6.49180923e-01, -1.40162656e+00, -5.47154397e-01,
        4.73110873e-01, -1.36336661e+00,  3.58331030e-01, -1.22308014e+00,
        1.39915019e-02, -3.70217616e-02, -9.55260504e-01, -6.36427608e-01,
       -1.39048289e-01, -2.42684457e-02,  2.05291240e-01, -1.00627377e+00,
        5.87890716e-01, -3.81361290e-01, -8.02220714e-01, -1.33785998e+00,
        1.16018029e-01, -1.28684672e+00,  1.64641593e+00,  3.07317767e-01,
        8.30203718e-01,  5.87890716e-01, -5.21647765e-01, -5.21647765e-01,
       -1.15931356e+00, -5.08894449e-01, -3.55854658e-01,  1.53163609e+00,
       -8.40480662e-01,  2.00350878e+00, -9.04247241e-01, -1.05728703e+00,
       -2.53828131e-01,  1.14903661e+00, -1.13380693e+00,  2.43551188e-01,
       -1.23583345e+00, -1.09554698e+00, -1.64554920e-01,  1.48062283e+00,
       -2.53828131e-01,  6.13397348e-01, -7.52817092e-02, -1.14656024e+00,
        1.88872894e+00])

In [21]:
y_test_scaled

array([ 0.83020372, -1.07004035,  0.61339735,  0.97049019, -0.5471544 ,
       -0.89149393,  1.12352998,  1.50612946, -0.76396077, -0.73845413,
       -0.76396077,  1.25106314, -0.70019419,  1.82496236, -0.24107482,
       -1.10830029,  1.79945572,  1.40410293,  0.20529124,  1.54438941,
        1.99075546, -1.14656024, -0.33034803,  0.99599682, -0.31759471,
       -0.45788119,  1.39134962, -0.98076714, -1.3506133 , -0.59816766,
       -0.17730824, -0.52164776, -0.81497403,  0.12877134,  0.3328244 ,
        1.00875014, -1.42713319, -0.89149393,  0.23079787, -1.15931356,
       -1.3506133 , -0.58541434,  0.02674482,  0.17978461, -0.81497403,
       -1.29960003,  0.58789072, -0.85323398, -0.81497403,  1.32758304,
       -0.2283215 ,  0.05225145, -1.08279366, -1.04453372,  0.21804456,
       -0.75120745, -1.04453372, -0.03702176,  0.17978461, -1.19757351,
       -0.40686792, -1.29960003,  0.42209761, -0.66193424,  0.76643714,
        1.20004988,  0.34557771, -0.55990771, -0.17730824,  0.61339735,
       -0.67468756,  0.86846367,  1.6209093 , -1.18482019, -0.82772735,
       -0.80222071,  0.40934429,  0.84295703,  1.0597634 ,  1.00875014,
       -1.09554698,  0.46035756, -0.73845413, -1.04453372, -0.01151513,
       -0.7129475 , -1.49089977, -1.15931356,  0.38383766, -0.12629497,
       -0.04977508,  1.60815599, -0.36860797, -1.21032682, -1.13380693,
        1.6209093 ,  1.56989604,  0.16703129, -0.81497403, -1.04453372,
        0.30731777, -0.84048066,  1.48062283, -0.67468756,  0.54963077,
       -0.72570082, -1.28684672, -1.05728703,  1.3785963 , -1.29960003,
       -0.66193424,  0.15427798,  0.44760424,  0.24355119,  0.84295703,
        0.66441061, -0.72570082, -1.19757351, -1.18482019,  1.12352998,
       -0.41962124, -0.33034803, -0.63642761,  1.41685625, -0.27933476,
        1.64641593,  0.2563045 , -0.31759471,  1.31482972, -0.21556818,
       -1.15931356, -0.77671408,  0.99599682])

In [24]:
model=SVR()
model.fit(X_train,y_train_scaled)

SVR()

In [25]:
y_pred_scaled=model.predict(X_test)

In [27]:
r2_score(y_test_scaled,y_pred_scaled)

0.48844443151651884

In [28]:
# Linear model
model=SVR(kernel="linear")
model.fit(X_train,y_train_scaled)
y_pred_scaled=model.predict(X_test)
r2_score(y_test_scaled,y_pred_scaled)

0.4433761323833776

In [31]:
model=SVR(kernel="sigmoid")
model.fit(X_train,y_train_scaled)
y_pred_scaled=model.predict(X_test)
r2_score(y_test_scaled,y_pred_scaled)

-15.316808189576822

In [32]:
model=SVR(kernel="poly")
model.fit(X_train,y_train_scaled)
y_pred_scaled=model.predict(X_test)
r2_score(y_test_scaled,y_pred_scaled)

0.24203771038107758

In [35]:
# overfitiing is happening lets do next step
# Hyperparameter tuning with gridsearch cv

from sklearn.model_selection import GridSearchCV




param_grid = {
    'kernel': ['linear', 'rbf'],
    'C': [1,2,5,10,50,100],
    'epsilon': [0.01,0.1,0.2,0.3,0.5]
}



svr=SVR()

grid_search = GridSearchCV(svr, param_grid, cv=3,scoring="r2")
grid_search.fit(X_train, y_train_scaled)

print(grid_search.best_params_)

{'C': 10, 'epsilon': 0.01, 'kernel': 'linear'}

In [40]:
best_model=SVR(kernel="linear",C=10,epsilon=0.01)
best_model.fit(X_train,y_train_scaled)
y_pred_scaled=best_model.predict(X_test)
y_train_pred_scaled=best_model.predict(X_train)
r2_score(y_test_scaled,y_pred_scaled)

0.467019368762416

In [41]:
r2_score(y_train_scaled,y_train_pred_scaled)

0.5136151195083838

In [42]:
# here train and test r2 score is close so no overfitting hence best case

In [45]:
from sklearn.svm import LinearSVR

model=LinearSVR(C=10,epsilon=0.1,max_iter=5000)
model.fit(X_train,y_train_scaled)

y_pred_scaled=best_model.predict(X_test)
y_train_pred_scaled=best_model.predict(X_train)
r2_score(y_test_scaled,y_pred_scaled)

0.467019368762416

In [46]:
r2_score(y_train_scaled,y_train_pred_scaled)

0.5136151195083838