In [61]:
import pandas as pd

In [62]:
df=pd.read_csv("IMDB_Dataset.csv")

In [63]:
df.shape

(50000, 2)

In [64]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [65]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [66]:
df.drop_duplicates(inplace=True)

In [67]:
df.shape

(49582, 2)

In [68]:
# Preprocessing

In [69]:
# convert to lowercase

In [70]:
df["review"]=df["review"].str.lower()

In [71]:
# removing urls

In [72]:
import re

def remove_urls(text):
    text=re.sub(r"http\S+","",text)  #pattern,repl,string
    return text 
df["review"]=df["review"].apply(remove_urls)

In [73]:
# Removing punctuations
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. <br /><br />the...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

In [74]:
def remove_punctuations(text):
    text = re.sub(r"[^A-Za-z0-9\s]" ,"", text) # A-Z a-z 0-9 \s
    return text

df["review"] = df["review"].apply(remove_punctuations)

In [75]:
def remove_html(text):
    text = re.sub(r"<.*?>" ,"", text)
    return text

df["review"] = df["review"].apply(remove_html)

In [76]:
# Remoing stopwords

In [77]:
import nltk

nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("stopwords")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\karun\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\karun\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\karun\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [78]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [79]:
def remove_stopwords(text):
    tokens = word_tokenize(text)
    stop_words = stopwords.words("english")

    for word in tokens:
        if word in stop_words:
            text = text.replace(word, "")

    return text

df["review"] = df["review"].apply(remove_stopwords)

In [80]:
df.head()

                                              review sentiment
0  e    revewers  nted   wtchg  1 oz epode ll  ho...  positive
1   wderful ltle producti br br  filming techniqu...  positive
2   thought ths   wderful wy  spend tme   o hot s...  positive
3  bsclly res  fmly   lttle boy jke thks res  zom...  negative
4  petter mtte love   time  mey   vully stunng fi...  positive

In [81]:
# running -> run
# played -> play
# PorterStemming

from nltk.stem import PorterStemmer

In [82]:
def stemming(text):
    ps = PorterStemmer()
    stemmed_words = []

    tokens = word_tokenize(text)
    for token in tokens:
        stemmed_token = ps.stem(token)
        stemmed_words.append(stemmed_token)

    return " ".join(stemmed_words)

df["review"] = df["review"].apply(stemming)

In [83]:
df.head()

                                              review sentiment
0  e revew nted wtchg 1 oz epod ll hook y rght ex...  positive
1  wder ltle producti br br film techniqu unssum ...  positive
2  thought th wder wy spend tme o hot summer week...  positive
3  bsclli re fmli lttle boy jke thk re zomb close...  negative
4  petter mtte love time mey vulli stunng film wt...  positive

In [84]:
# Encoding

In [85]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df["sentiment"] = le.fit_transform(df["sentiment"])

In [86]:
y = df["sentiment"]

In [87]:
y

0        1
1        1
2        1
3        0
4        1
        ..
49995    1
49996    0
49997    0
49998    0
49999    0
Name: sentiment, Length: 49582, dtype: int64

In [88]:
from sklearn.feature_extraction.text import TfidfVectorizer

tf = TfidfVectorizer(max_features=5000)

X = tf.fit_transform(df["review"])

In [89]:
X

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4057140 stored elements and shape (49582, 5000)>

In [90]:
## Dataset & Data Loaders

In [91]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [92]:
X_train.shape

(39665, 5000)

In [93]:
X_test.shape

(9917, 5000)

In [94]:
import torch
from torch.utils.data import TensorDataset, DataLoader

In [95]:
X_train = X_train.toarray()
X_test = X_test.toarray()

In [96]:
train_set = TensorDataset(
    torch.from_numpy(X_train).float(),
    torch.from_numpy(y_train.values).float()
)

test_set = TensorDataset(
    torch.from_numpy(X_test).float(),
    torch.from_numpy(y_test.values).float()
)

C:\Users\karun\AppData\Local\Temp\ipykernel_36248\2931448922.py:3: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\torch\csrc\utils\tensor_numpy.cpp:219.)
  torch.from_numpy(y_train.values).float()

In [97]:
train_loader = DataLoader(train_set, shuffle=True, batch_size=64)
test_loader = DataLoader(test_set, shuffle=True, batch_size=64)

In [98]:
import torch.nn as nn
import torch.optim as optim

In [99]:
class RNN(nn.Module):
    def __init__(self, input_size, hidden_size=128, num_layers=1):
        super().__init__()

        self.hidden_size = hidden_size
        self.num_layers = num_layers

        # RNN layer
        self.rnn = nn.RNN(input_size, hidden_size, num_layers, batch_first=True)

        # fully connected layer
        self.fc = nn.Linear(hidden_size, 1)

    def forward(self, x):
        # optional => shape (num of layers, batch size, hidden size)
        h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size)

        out, _ = self.rnn(x, h0) 
        # 1st value = hidden state of all the timesteps => (batch, seq_len, hidden size)
        # 2nd value = final hidden state of last timestep

        out = self.fc(out[:, -1, :])
        return out

In [100]:
input_size = X_train.shape[1]

model = RNN(input_size)

criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters())

In [101]:
# Training RNN
epochs = 10

for epoch in range(epochs):
    model.train()

    for Xb, yb in train_loader:
        optimizer.zero_grad()

        Xb = Xb.unsqueeze(1) # add singleton direction
        
        outputs = model(Xb) # (batch_size, 1)

        outputs = torch.sigmoid(outputs.squeeze()) # (batch_size,) => probability

        loss = criterion(outputs, yb) # compute loss
        loss.backward() # backprop
        optimizer.step() # weights update

    print(f"epoch = {epoch+1}/{epochs} and loss = {loss.item()}")

epoch = 1/10 and loss = 0.21376532316207886
epoch = 2/10 and loss = 0.21096579730510712
epoch = 3/10 and loss = 0.20748759806156158
epoch = 4/10 and loss = 0.1774880737066269
epoch = 5/10 and loss = 0.26958972215652466
epoch = 6/10 and loss = 0.21606580913066864
epoch = 7/10 and loss = 0.2553306221961975
epoch = 8/10 and loss = 0.19906604290008545
epoch = 9/10 and loss = 0.1942095309495926
epoch = 10/10 and loss = 0.14498242735862732

In [102]:
# evaluate

model.eval()

with torch.no_grad():
    correct_vals = 0
    tot_vals = 0
    
    for Xb, yb in test_loader:
        Xb = Xb.unsqueeze(1)

        outputs = model(Xb)
        predicted = (torch.sigmoid(outputs.squeeze()) > 0.5).float()

        tot_vals += yb.size(0)
        correct_vals += (predicted == yb).sum().item()

    print(f"accuracy = {correct_vals/tot_vals*100}")

accuracy = 85.6206514066754